[tool.poetry]
name = "chat"
version = "0.1.0"
description = ""
authors = ["Dishalex <dishalex@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
websockets = "^11.0.3"
names = "^0.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
